# Generated by Django 2.2.12 on 2020-04-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='prod_images')),
                ('desc', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('is_stock_available', models.BooleanField(default=True)),
            ],
        ),
    ]
